config/routes.rb
Rails.application.routes.draw do

  resources :meetings

  resources :complaints

  resources :tenants

  resources :vender_regs

  resources :attendances

  resources :noticeboards

  resources :committmemregs

  resources :membersearches

  resources :memberachives

  resources :classifieds

  resources :discountdetails

  resources :bankaccounts

  resources :members

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
end

app/models/bankaccount.rb
# == Schema Information
#
# Table name: bankaccounts
#
#  id           :integer          not null, primary key
#  acc_no       :integer
#  acc_name     :string
#  bank_name    :string
#  bank_branch  :string
#  bank_add     :text
#  bank_balance :float
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Bankaccount < ActiveRecord::Base
end

app/models/classified.rb
class Classified < ActiveRecord::Base
end

app/models/committmemreg.rb
class Committmemreg < ActiveRecord::Base
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/discountdetail.rb
# == Schema Information
#
# Table name: discountdetails
#
#  id              :integer          not null, primary key
#  discount_desc   :text
#  disfix_amt      :float
#  dis_percentages :float
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Discountdetail < ActiveRecord::Base
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id              :integer          not null, primary key
#  firstname       :string
#  lastname        :string
#  email           :string
#  landlineno      :string
#  mobileno        :string
#  dob             :date
#  gender          :string
#  age             :integer
#  nooffamily      :integer
#  profession      :string
#  pancardno       :string
#  address         :text
#  phasename       :string
#  subphase        :string
#  flatno          :integer
#  flattype        :string
#  flatarea        :float
#  parkingno       :integer
#  nooftwowheeler  :integer
#  nooffourwheeler :integer
#  username        :string
#  password        :string
#  cpassword       :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Member < ActiveRecord::Base
end

app/models/memberachive.rb
class Memberachive < ActiveRecord::Base
end

app/models/membersearch.rb
class Membersearch < ActiveRecord::Base
end

app/models/noticeboard.rb
class Noticeboard < ActiveRecord::Base
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
end

app/models/vender_reg.rb
class VenderReg < ActiveRecord::Base
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:phase, :pointsdiscussed, :dateandtime, :venue, :conclusion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/bankaccounts_helper.rb
module BankaccountsHelper
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/vender_regs_helper.rb
module VenderRegsHelper
end

app/views/meetings/_form.html.erb
<html>
  <body>
   <div class="container">
    <div class="jumbotron">
      <h2>Post Complain</h2>
        <%= form_for(@meeting) do |f| %>
          <% if @meeting.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2><ul>
                <% @meeting.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="form-group">
          <label type="text">Phase Name</label>
            <%= f.text_field :phase, autofocus: true, :class => "form-control" , :placeholder=>"Enter Phase Name"%>
        </div>
    
 <div class="form-group">
  <label type="text">Permanant Address</label>
  <%= f.text_area :pointsdiscussed, :class=>"form-control" %>
</div>
  
  <div class="field">
  <label type="text">Meeting Date and Time</label><br>
    <%= f.datetime_select :dateandtime %>
  </div>

  <div class="form-group">
    <label type="text">Venue</label>
    <%= f.text_field :venue, autofocus: true, :class => "form-control" , :placeholder=>"Enter Venue"%>
</div>

  
 <div class="form-group">
  <label type="text">Conclusion</label>
  <%= f.text_area :conclusion, :class=>"form-control" %>
</div>
 <div class="actions">
  <%= f.submit 'Add Meeting', :class=>"btn"%>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Phase</th>
      <th>Pointsdiscussed</th>
      <th>Dateandtime</th>
      <th>Venue</th>
      <th>Conclusion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.phase %></td>
        <td><%= meeting.pointsdiscussed %></td>
        <td><%= meeting.dateandtime %></td>
        <td><%= meeting.venue %></td>
        <td><%= meeting.conclusion %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phase:</strong>
  <%= @meeting.phase %>
</p>

<p>
  <strong>Pointsdiscussed:</strong>
  <%= @meeting.pointsdiscussed %>
</p>

<p>
  <strong>Dateandtime:</strong>
  <%= @meeting.dateandtime %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @meeting.venue %>
</p>

<p>
  <strong>Conclusion:</strong>
  <%= @meeting.conclusion %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>