config/routes.rb
Rails.application.routes.draw do

  resources :meetings

  resources :complaints

  resources :tenants

  resources :vender_regs

  resources :attendances

  resources :noticeboards

  resources :committmemregs

  resources :membersearches

  resources :memberachives

  resources :classifieds

  resources :discountdetails

  resources :bankaccounts

  resources :members

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
end

app/models/bankaccount.rb
# == Schema Information
#
# Table name: bankaccounts
#
#  id           :integer          not null, primary key
#  acc_no       :integer
#  acc_name     :string
#  bank_name    :string
#  bank_branch  :string
#  bank_add     :text
#  bank_balance :float
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Bankaccount < ActiveRecord::Base
end

app/models/classified.rb
class Classified < ActiveRecord::Base
end

app/models/committmemreg.rb
class Committmemreg < ActiveRecord::Base
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/discountdetail.rb
# == Schema Information
#
# Table name: discountdetails
#
#  id              :integer          not null, primary key
#  discount_desc   :text
#  disfix_amt      :float
#  dis_percentages :float
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Discountdetail < ActiveRecord::Base
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id              :integer          not null, primary key
#  firstname       :string
#  lastname        :string
#  email           :string
#  landlineno      :string
#  mobileno        :string
#  dob             :date
#  gender          :string
#  age             :integer
#  nooffamily      :integer
#  profession      :string
#  pancardno       :string
#  address         :text
#  phasename       :string
#  subphase        :string
#  flatno          :integer
#  flattype        :string
#  flatarea        :float
#  parkingno       :integer
#  nooftwowheeler  :integer
#  nooffourwheeler :integer
#  username        :string
#  password        :string
#  cpassword       :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Member < ActiveRecord::Base
end

app/models/memberachive.rb
class Memberachive < ActiveRecord::Base
end

app/models/membersearch.rb
class Membersearch < ActiveRecord::Base
end

app/models/noticeboard.rb
class Noticeboard < ActiveRecord::Base
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
end

app/models/vender_reg.rb
class VenderReg < ActiveRecord::Base
end

app/controllers/vender_regs_controller.rb
class VenderRegsController < ApplicationController
  before_action :set_vender_reg, only: [:show, :edit, :update, :destroy]

  # GET /vender_regs
  # GET /vender_regs.json
  def index
    @vender_regs = VenderReg.all
  end

  # GET /vender_regs/1
  # GET /vender_regs/1.json
  def show
  end

  # GET /vender_regs/new
  def new
    @vender_reg = VenderReg.new
  end

  # GET /vender_regs/1/edit
  def edit
  end

  # POST /vender_regs
  # POST /vender_regs.json
  def create
    @vender_reg = VenderReg.new(vender_reg_params)

    respond_to do |format|
      if @vender_reg.save
        format.html { redirect_to @vender_reg, notice: 'Vender reg was successfully created.' }
        format.json { render :show, status: :created, location: @vender_reg }
      else
        format.html { render :new }
        format.json { render json: @vender_reg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vender_regs/1
  # PATCH/PUT /vender_regs/1.json
  def update
    respond_to do |format|
      if @vender_reg.update(vender_reg_params)
        format.html { redirect_to @vender_reg, notice: 'Vender reg was successfully updated.' }
        format.json { render :show, status: :ok, location: @vender_reg }
      else
        format.html { render :edit }
        format.json { render json: @vender_reg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vender_regs/1
  # DELETE /vender_regs/1.json
  def destroy
    @vender_reg.destroy
    respond_to do |format|
      format.html { redirect_to vender_regs_url, notice: 'Vender reg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vender_reg
      @vender_reg = VenderReg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vender_reg_params
      params.require(:vender_reg).permit(:Name, :Address, :Contact_no, :DOB, :Gender, :Vendor_inside, :vender_type, :Contracter_Name, :Contracter_N0, :Contracter_period, :Contract_Start_Date, :Pan_No, :Service_Tax, :TDS, :Salary, :Vendor_Outside, :Vendor_Type, :Owner_Name, :Tenant_Name, :Flat_no)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/bankaccounts_helper.rb
module BankaccountsHelper
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/vender_regs_helper.rb
module VenderRegsHelper
end

app/views/vender_regs/_form.html.erb
<html>
  <body>
   <div class="container">
    <div class="jumbotron">

    <h1><b>Vender Form</b></h1>

              <%= form_for(@vender_reg) do |f| %>
                <% if @vender_reg.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@vender_reg.errors.count, "error") %> prohibited this vender_reg from being saved:</h2>

                    <ul>
                    <% @vender_reg.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>



        <div class="field">
                <%= f.label :Name %><br>
                <%= f.text_field :Name,autofocus: true, :class => "form-control" , :placeholder=>"Enter firstname"%>
        </div>

          <div class="field">
                  <%= f.label :Address %><br>
                  <%= f.text_area :Address,:class => "form-control"%>
          </div>
          <div class="field">
                   <%= f.label :Contact_no %><br>
                    <%= f.text_field :Contact_no,:class => "form-control"%>
          </div>
                    <div class="field">
                    <%= f.label :Date_Of_Birth %><br>
                    <%= f.date_select :DOB,:class => "form-control"%>
          </div>
         <div class="form-group">
           <label for="gender">Gender:</label>
           <%= radio_button :member, :gender, :Male%>Male
           <%= radio_button :member, :gender, :Female%>Female
         </div>
 <!--  <div class="field">
    <%= f.label :Gender %><br>
    <%= f.text_field :Gender %>
  </div> -->
  <div class="field">
    <%= f.label :Vendor_inside %>
    <%= f.check_box :Vendor_inside %>
  </div>
  <div class="field">
    <%= f.label :vender_type %><br>
    <%= f.text_field :vender_type,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :Contracter_Name %><br>
    <%= f.text_field :Contracter_Name,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :Contracter_N0 %><br>
    <%= f.text_field :Contracter_N0,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :Contracter_period %><br>
    <%= f.number_field :Contracter_period %>
  </div>
  <div class="field">
    <%= f.label :Contract_Start_Date %><br>
    <%= f.date_select :Contract_Start_Date %>
  </div>
  <div class="field">
    <%= f.label :Pan_No %><br>
    <%= f.text_field :Pan_No,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :Service_Tax %><br>
    <%= f.text_field :Service_Tax,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :TDS %><br>
    <%= f.text_field :TDS,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :Salary %><br>
    <%= f.text_field :Salary,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :Vendor_Outside %>
    <%= f.check_box :Vendor_Outside %>
  </div>
  <div class="field">
    <%= f.label :Vendor_Type %><br>
    <%= f.text_field :Vendor_Type,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :Owner_Name %><br>
    <%= f.text_field :Owner_Name,:class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :Tenant_Name %><br>
    <%= f.text_field :Tenant_Name,:class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :Flat_no %><br>
    <%= f.number_field :Flat_no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vender_regs/edit.html.erb
<br><br>
<br><br>

<%= render 'form' %>

<%= link_to 'Show', @vender_reg %> |
<%= link_to 'Back', vender_regs_path %>

app/views/vender_regs/index.html.erb
<html>
  <body>
   <div class="container">

<p id="notice"><%= notice %></p>
<br><br>
<h1>Listing Vender Regs</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Contact no</th>
      <th>Dath Of Birth</th>
      <th>Gender</th>
      <th>Vendor inside</th>
      <th>Vender type</th>
      <th>Contracter name</th>
      <th>Contracter n0</th>
      <th>Contracter period</th>
      <th>Contract start date</th>
      <th>Pan no</th>
      <th>Service tax</th>
      <th>Tds</th>
      <th>Salary</th>
      <th>Vendor outside</th>
      <th>Vendor type</th>
      <th>Owner name</th>
      <th>Tenant name</th>
      <th>Flat no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vender_regs.each do |vender_reg| %>
      <tr>
        <td><%= vender_reg.Name %></td>
        <td><%= vender_reg.Address %></td>
        <td><%= vender_reg.Contact_no %></td>
        <td><%= vender_reg.DOB %></td>
        <td><%= vender_reg.Gender %></td>
        <td><%= vender_reg.Vendor_inside %></td>
        <td><%= vender_reg.vender_type %></td>
        <td><%= vender_reg.Contracter_Name %></td>
        <td><%= vender_reg.Contracter_N0 %></td>
        <td><%= vender_reg.Contracter_period %></td>
        <td><%= vender_reg.Contract_Start_Date %></td>
        <td><%= vender_reg.Pan_No %></td>
        <td><%= vender_reg.Service_Tax %></td>
        <td><%= vender_reg.TDS %></td>
        <td><%= vender_reg.Salary %></td>
        <td><%= vender_reg.Vendor_Outside %></td>
        <td><%= vender_reg.Vendor_Type %></td>
        <td><%= vender_reg.Owner_Name %></td>
        <td><%= vender_reg.Tenant_Name %></td>
        <td><%= vender_reg.Flat_no %></td>
        <td><%= link_to 'Show', vender_reg, class: 'btn' %></td>
        <td><%= link_to 'Edit', edit_vender_reg_path(vender_reg), class: 'btn' %></td>
        <td><%= link_to 'Destroy', vender_reg, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vender reg', new_vender_reg_path %>
</div>
</body>
</html>

app/views/vender_regs/new.html.erb
<h1>New Vender Reg</h1>

<%= render 'form' %>

<%= link_to 'Back', vender_regs_path %>

app/views/vender_regs/show.html.erb
<html>
  <body>
    <br><br><br><br>
   <div class="container">
    <div class="jumbotron">
              <p id="notice"><%= notice %></p>


<table class= "table">

              <p><tr>
                <td><strong>Name:</strong></td>
                 <td><%= @vender_reg.Name %></td>
              </tr></p>

              <p><tr>
                 <td><strong>Address:</strong></td>
                 <td><%= @vender_reg.Address %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Contact no:</strong></td>
                 <td><%= @vender_reg.Contact_no %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Dob:</strong></td>
                 <td><%= @vender_reg.DOB %></td>
             </tr></p>

              <p><tr>
                 <td><strong>Gender:</strong></td>
                 <td><%= @vender_reg.Gender %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Vendor inside:</strong></td>
                 <td><%= @vender_reg.Vendor_inside %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Vender type:</strong></td>
                <td><%= @vender_reg.vender_type %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Contracter name:</strong></td>
                 <td><%= @vender_reg.Contracter_Name %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Contracter n0:</strong></td>
                 <td><%= @vender_reg.Contracter_N0 %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Contracter period:</strong></td>
                 <td><%= @vender_reg.Contracter_period %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Contract start date:</strong></td>
                 <td><%= @vender_reg.Contract_Start_Date %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Pan no:</strong></td>
                 <td><%= @vender_reg.Pan_No %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Service tax:</strong></td>
                 <td><%= @vender_reg.Service_Tax %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Tds:</strong></td>
                 <td><%= @vender_reg.TDS %></td>
              </tr></p>

              <p><tr>
                 <td><strong>Salary:</strong></td>
                 <td><%= @vender_reg.Salary %></td>
              </tr> </p>

              <p><tr>
                 <td><strong>Vendor outside:</strong></td>
                 <td><%= @vender_reg.Vendor_Outside %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Vendor type:</strong></td>
                 <td><%= @vender_reg.Vendor_Type %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Owner name:</strong></td>
                 <td><%= @vender_reg.Owner_Name %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Tenant name:</strong></td>
                 <td><%= @vender_reg.Tenant_Name %></td>
               </tr></p>

              <p><tr>
                 <td><strong>Flat no:</strong></td>
                 <td><%= @vender_reg.Flat_no %></td>
              </tr></p>
              </table>

              <%= link_to 'Edit', edit_vender_reg_path(@vender_reg), class: 'btn' %> |
              <%= link_to 'Back', vender_regs_path, class: 'btn'  %>
</div>
</div>
</body>
</html>