config/routes.rb
Rails.application.routes.draw do

  resources :meetings

  resources :complaints

  resources :tenants

  resources :vender_regs

  resources :attendances

  resources :noticeboards

  resources :committmemregs

  resources :membersearches

  resources :memberachives

  resources :classifieds

  resources :discountdetails

  resources :bankaccounts

  resources :members

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
end

app/models/bankaccount.rb
# == Schema Information
#
# Table name: bankaccounts
#
#  id           :integer          not null, primary key
#  acc_no       :integer
#  acc_name     :string
#  bank_name    :string
#  bank_branch  :string
#  bank_add     :text
#  bank_balance :float
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Bankaccount < ActiveRecord::Base
end

app/models/classified.rb
class Classified < ActiveRecord::Base
end

app/models/committmemreg.rb
class Committmemreg < ActiveRecord::Base
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/discountdetail.rb
# == Schema Information
#
# Table name: discountdetails
#
#  id              :integer          not null, primary key
#  discount_desc   :text
#  disfix_amt      :float
#  dis_percentages :float
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Discountdetail < ActiveRecord::Base
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id              :integer          not null, primary key
#  firstname       :string
#  lastname        :string
#  email           :string
#  landlineno      :string
#  mobileno        :string
#  dob             :date
#  gender          :string
#  age             :integer
#  nooffamily      :integer
#  profession      :string
#  pancardno       :string
#  address         :text
#  phasename       :string
#  subphase        :string
#  flatno          :integer
#  flattype        :string
#  flatarea        :float
#  parkingno       :integer
#  nooftwowheeler  :integer
#  nooffourwheeler :integer
#  username        :string
#  password        :string
#  cpassword       :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Member < ActiveRecord::Base
end

app/models/memberachive.rb
class Memberachive < ActiveRecord::Base
end

app/models/membersearch.rb
class Membersearch < ActiveRecord::Base
end

app/models/noticeboard.rb
class Noticeboard < ActiveRecord::Base
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
end

app/models/vender_reg.rb
class VenderReg < ActiveRecord::Base
end

app/controllers/committmemregs_controller.rb
class CommittmemregsController < ApplicationController
  before_action :set_committmemreg, only: [:show, :edit, :update, :destroy]

  # GET /committmemregs
  # GET /committmemregs.json
  def index
    @committmemregs = Committmemreg.all
  end

  # GET /committmemregs/1
  # GET /committmemregs/1.json
  def show
  end

  # GET /committmemregs/new
  def new
    @committmemreg = Committmemreg.new
  end

  # GET /committmemregs/1/edit
  def edit
  end

  # POST /committmemregs
  # POST /committmemregs.json
  def create
    @committmemreg = Committmemreg.new(committmemreg_params)

    respond_to do |format|
      if @committmemreg.save
        format.html { redirect_to @committmemreg, notice: 'Committmemreg was successfully created.' }
        format.json { render :show, status: :created, location: @committmemreg }
      else
        format.html { render :new }
        format.json { render json: @committmemreg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /committmemregs/1
  # PATCH/PUT /committmemregs/1.json
  def update
    respond_to do |format|
      if @committmemreg.update(committmemreg_params)
        format.html { redirect_to @committmemreg, notice: 'Committmemreg was successfully updated.' }
        format.json { render :show, status: :ok, location: @committmemreg }
      else
        format.html { render :edit }
        format.json { render json: @committmemreg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /committmemregs/1
  # DELETE /committmemregs/1.json
  def destroy
    @committmemreg.destroy
    respond_to do |format|
      format.html { redirect_to committmemregs_url, notice: 'Committmemreg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_committmemreg
      @committmemreg = Committmemreg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def committmemreg_params
      params.require(:committmemreg).permit(:Full_Name, :Gender, :Role, :Email, :Phase_No, :Responsible_For, :Start_Date, :Duration)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/helpers/committmemregs_helper.rb
module CommittmemregsHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/vender_regs_helper.rb
module VenderRegsHelper
end

app/views/committmemregs/_form.html.erb
<html>
  <body>
   <div class="container">
    <div class="jumbotron">
      <h2>Committ Member Registration</h2>
<%= form_for(@committmemreg) do |f| %>
  <% if @committmemreg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@committmemreg.errors.count, "error") %> prohibited this committmemreg from being saved:</h2>

      <ul>
      <% @committmemreg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<div class="form-group">
    <%= f.label :Full_Name %>
    <%= f.text_field :Full_Name, autofocus: true, :class => "form-control" , :placeholder=>"Enter fullname"%>
  </div>
<!--   <div class="field">
    <%= f.label :Full_Name %><br>
    <%= f.text_field :Full_Name %>
  </div> -->

  <div class="form-group">
   <label for="gender">Gender:</label>
   <%= radio_button :member, :gender, :Male%>Male
   <%= radio_button :member, :gender, :Female%>Female
 </div>
<!--   <div class="field">
    <%= f.label :Gender %><br>
    <%= f.text_field :Gender %>
  </div> -->

<div class="form-group">
    <%= f.label :Role %>
    <%= f.text_field :Role, autofocus: true, :class => "form-control" , :placeholder=>"Enter Role"%>
  </div>
<!--   <div class="field">
    <%= f.label :Role %><br>
    <%= f.text_field :Role %>
  </div> -->
  <div class="form-group">
    <%= f.label :Email %>
    <%= f.text_field :Email, autofocus: true, :class => "form-control" , :placeholder=>"Enter email"%>
  </div>
 <!--  <div class="field">
    <%= f.label :Email %><br>
    <%= f.text_field :Email %>
  </div> -->
  <!-- <div class="field">
    <%= f.label :Phase_No %><br>
    <%= f.number_field :Phase_No %>
  </div> -->
   <div class="form-group">
    <%= f.label :Phase_No %>
    <%= f.number_field :Phase_No, autofocus: true, :class => "form-control" , :placeholder=>"Enter Phase_No"%>
 </div>

<div class="form-group">
  <%= f.label :Responsible_For %>
  <%= f.text_area :Responsible_For, :class=>"form-control" %>
</div>
  <!-- <div class="field">
    <%= f.label :Responsible_For %><br>
    <%= f.text_area :Responsible_For %>
  </div> -->  
  <div class="form-group">
    <%= f.label :Start_Date %>
    <%= f.date_select :Start_Date ,:class => "form-control"  %>
  </div>
   <!-- <div class="field">
    <%= f.label :Start_Date %><br>
    <%= f.date_select :Start_Date %>
  </div> -->
   <div class="form-group">
    <%= f.label :Duration %>
    <%= f.number_field :Duration, autofocus: true, :class => "form-control" , :placeholder=>"Enter Duration"%>
 </div>
  <!-- <div class="field">
    <%= f.label :Duration %><br>
    <%= f.number_field :Duration %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/committmemregs/edit.html.erb
<h1>Editing Committmemreg</h1>

<%= render 'form' %>

<%= link_to 'Show', @committmemreg %> |
<%= link_to 'Back', committmemregs_path %>

app/views/committmemregs/index.html.erb
<html>
  <body><br>
<br>
  <div class="jumbotron">
   <div class="container">

<br>

<p id="notice"><%= notice %></p>

<h1>Listing Committ Member registration</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Full name</th>
      <th>Gender</th>
      <th>Role</th>
      <th>Email</th>
      <th>Phase no</th>
      <th>Responsible for</th>
      <th>Start date</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @committmemregs.each do |committmemreg| %>
      <tr>
        <td><%= committmemreg.Full_Name %></td>
        <td><%= committmemreg.Gender %></td>
        <td><%= committmemreg.Role %></td>
        <td><%= committmemreg.Email %></td>
        <td><%= committmemreg.Phase_No %></td>
        <td><%= committmemreg.Responsible_For %></td>
        <td><%= committmemreg.Start_Date %></td>
        <td><%= committmemreg.Duration %></td>
        <td><%= link_to 'Show', committmemreg, class: 'btn' %></td>
        <td><%= link_to 'Edit', edit_committmemreg_path(committmemreg), class: 'btn' %></td>
        <td><%= link_to 'Destroy', committmemreg, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Committmemreg', new_committmemreg_path, class: 'btn' %>
</div>
</div>
</body>
</html>

app/views/committmemregs/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', committmemregs_path %>

app/views/committmemregs/show.html.erb
<html>
  <body><br>
<br><br><br>
  <div class="jumbotron">
   <div class="container">


<p id="notice"><%= notice %></p>
<table class="table">

<p><tr>
  <td><strong>Full name:</strong></td>
  <td><%= @committmemreg.Full_Name %></td>
</tr></p>

<p><tr>
  <td><strong>Gender:</strong></td>
  <td><%= @committmemreg.Gender %></td>
</tr></p>

<p><tr>
  <td><strong>Role:</strong></td>
  <td><%= @committmemreg.Role %></td>
</tr></p>

<p><tr>
  <td><strong>Email:</strong></td>
  <td><%= @committmemreg.Email %></td>
</tr></p>

<p><tr>
  <td><strong>Phase no:</strong></td>
  <td><%= @committmemreg.Phase_No %></td>
</tr></p>

<p><tr>
  <td><strong>Responsible for:</strong></td>
  <td><%= @committmemreg.Responsible_For %></td>
</tr></p>

<p><tr>
  <td><strong>Start date:</strong></td>
  <td><%= @committmemreg.Start_Date %></td>
</tr></p>

<p><tr>
  <td><strong>Duration:</strong></td>
  <td><%= @committmemreg.Duration %></td>
</tr></p>
</table>
<%= link_to 'Edit', edit_committmemreg_path(@committmemreg), class: 'btn' %> |
<%= link_to 'Back', committmemregs_path, class: 'btn' %>
</div>
</div>
</body>
</html>