config/routes.rb
Rails.application.routes.draw do

  resources :meetings

  resources :complaints

  resources :tenants

  resources :vender_regs

  resources :attendances

  resources :noticeboards

  resources :committmemregs

  resources :membersearches

  resources :memberachives

  resources :classifieds

  resources :discountdetails

  resources :bankaccounts

  resources :members

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
end

app/models/bankaccount.rb
# == Schema Information
#
# Table name: bankaccounts
#
#  id           :integer          not null, primary key
#  acc_no       :integer
#  acc_name     :string
#  bank_name    :string
#  bank_branch  :string
#  bank_add     :text
#  bank_balance :float
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Bankaccount < ActiveRecord::Base
end

app/models/classified.rb
class Classified < ActiveRecord::Base
end

app/models/committmemreg.rb
class Committmemreg < ActiveRecord::Base
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/discountdetail.rb
# == Schema Information
#
# Table name: discountdetails
#
#  id              :integer          not null, primary key
#  discount_desc   :text
#  disfix_amt      :float
#  dis_percentages :float
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Discountdetail < ActiveRecord::Base
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id              :integer          not null, primary key
#  firstname       :string
#  lastname        :string
#  email           :string
#  landlineno      :string
#  mobileno        :string
#  dob             :date
#  gender          :string
#  age             :integer
#  nooffamily      :integer
#  profession      :string
#  pancardno       :string
#  address         :text
#  phasename       :string
#  subphase        :string
#  flatno          :integer
#  flattype        :string
#  flatarea        :float
#  parkingno       :integer
#  nooftwowheeler  :integer
#  nooffourwheeler :integer
#  username        :string
#  password        :string
#  cpassword       :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Member < ActiveRecord::Base
end

app/models/memberachive.rb
class Memberachive < ActiveRecord::Base
end

app/models/membersearch.rb
class Membersearch < ActiveRecord::Base
end

app/models/noticeboard.rb
class Noticeboard < ActiveRecord::Base
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
end

app/models/vender_reg.rb
class VenderReg < ActiveRecord::Base
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  before_action :set_classified, only: [:show, :edit, :update, :destroy]

  # GET /classifieds
  # GET /classifieds.json
  def index
    @classifieds = Classified.all
  end

  # GET /classifieds/1
  # GET /classifieds/1.json
  def show
  end

  # GET /classifieds/new
  def new
    @classified = Classified.new
  end

  # GET /classifieds/1/edit
  def edit
  end

  # POST /classifieds
  # POST /classifieds.json
  def create
    @classified = Classified.new(classified_params)

    respond_to do |format|
      if @classified.save
        format.html { redirect_to @classified, notice: 'Classified was successfully created.' }
        format.json { render :show, status: :created, location: @classified }
      else
        format.html { render :new }
        format.json { render json: @classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classifieds/1
  # PATCH/PUT /classifieds/1.json
  def update
    respond_to do |format|
      if @classified.update(classified_params)
        format.html { redirect_to @classified, notice: 'Classified was successfully updated.' }
        format.json { render :show, status: :ok, location: @classified }
      else
        format.html { render :edit }
        format.json { render json: @classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifieds/1
  # DELETE /classifieds/1.json
  def destroy
    @classified.destroy
    respond_to do |format|
      format.html { redirect_to classifieds_url, notice: 'Classified was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classified
      @classified = Classified.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classified_params
      params.require(:classified).permit(:AddTitle, :Wing, :FlatNo, :ContactNo, :choose, :Rate, :Description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/bankaccounts_helper.rb
module BankaccountsHelper
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/vender_regs_helper.rb
module VenderRegsHelper
end

app/views/classifieds/_form.html.erb
<html>
  <body>
   <div class="container">
    <div class="jumbotron">
        <h2>classified</h2>
<%= form_for(@classified) do |f| %>
  <% if @classified.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classified.errors.count, "error") %> prohibited this classified from being saved:</h2>

      <ul>
      <% @classified.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :AddTitle %><br>
   <%= f.text_field :AddTitle, autofocus: true, :class => "form-control" , :placeholder=>"AddTitle"%>
  </div>
  <div class="field">
    <%= f.label :Wing %><br>
    <%= f.text_field :Wing %>
  </div>
  <div class="field">
    <%= f.label :FlatNo %><br>
    <%= f.number_field :FlatNo %>
  </div>
  <div class="field">
    <%= f.label :ContactNo %><br>
    <%= f.text_field :ContactNo %>
  </div>
  <div class="field">
    <%= f.label :choose %><br>
    <%= radio_button :classified, :choose, :Rent%>Rent
   <%= radio_button :classified, :choose, :Sell%>sell
  </div>
  <div class="field">
    <%= f.label :Rate %><br>
    <%= f.number_field :Rate %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
       <%= f.text_area :Description, autofocus: true, :class => "form-control" , :placeholder=>"Description"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
</div>
</div>
</body>
</html>

app/views/classifieds/edit.html.erb
<h1>Editing Classified</h1>

<%= render 'form' %>

<%= link_to 'Show', @classified %> |
<%= link_to 'Back', classifieds_path %>

app/views/classifieds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Classifieds</h1>

<table>
  <thead>
    <tr>
      <th>Addtitle</th>
      <th>Wing</th>
      <th>Flatno</th>
      <th>Contactno</th>
      <th>Choose</th>
      <th>Rate</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classifieds.each do |classified| %>
      <tr>
        <td><%= classified.AddTitle %></td>
        <td><%= classified.Wing %></td>
        <td><%= classified.FlatNo %></td>
        <td><%= classified.ContactNo %></td>
        <td><%= classified.choose %></td>
        <td><%= classified.Rate %></td>
        <td><%= classified.Description %></td>
        <td><%= link_to 'Show', classified %></td>
        <td><%= link_to 'Edit', edit_classified_path(classified) %></td>
        <td><%= link_to 'Destroy', classified, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classified', new_classified_path %>

app/views/classifieds/new.html.erb
<h1>New Classified</h1>

<%= render 'form' %>

<%= link_to 'Back', classifieds_path %>

app/views/classifieds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Addtitle:</strong>
  <%= @classified.AddTitle %>
</p>

<p>
  <strong>Wing:</strong>
  <%= @classified.Wing %>
</p>

<p>
  <strong>Flatno:</strong>
  <%= @classified.FlatNo %>
</p>

<p>
  <strong>Contactno:</strong>
  <%= @classified.ContactNo %>
</p>

<p>
  <strong>Choose:</strong>
  <%= @classified.choose %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @classified.Rate %>
</p>

<p>
  <strong>Description:</strong>
  <%= @classified.Description %>
</p>

<%= link_to 'Edit', edit_classified_path(@classified) %> |
<%= link_to 'Back', classifieds_path %>